plugins {
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
}

version = "${project.mod_version}-neoforge-${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = '2024.07.28'
        minecraftVersion = '1.21'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', "advanced_hud"
        }
    }

    mods {
        "advanced_hud" {
            sourceSet sourceSets.main
        }
    }
}


// Ensure the mixin configuration is correctly recognized
neoForge {
    // ... other config ...
}

// Add mixin configuration
sourceSets.main.resources {
    srcDir 'src/main/resources'
}


repositories {
    maven { url "https://maven.shedaniel.me/" }       // Cloth Config
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = 'UTF-8'
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


java {
    // withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

// Ensure the resources are processed
processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    var replaceProperties = [

            minecraft_version      : minecraft_version,
            neoforge_version       : neoforge_version,
            mod_version            : mod_version,
            mod_id                 : "advanced_hud",
            mod_name               : "Advanced HUD",
            mod_description        : "A client-sided HUD mod that shows info about the block/entity you are looking at.",
            mod_authors            : "yigit",
            mod_license            : "MIT"
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}