# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=1.20.1
forge_version=47.1.0
mappings_channel=official
mappings_version=1.20.1

# Mod Properties
mod_id=advanced_hud
mod_version=1.0.4
mod_group=com.yigit.advancedhud
mod_authors=Yigit Guven
mod_description=Client side Minecraft mod that adds a highly customizable HUD that provides dynamic info on whatever player is looking at.
mod_license=GNU GPL-v3.0

# Dependencies
cloth_config_version=11.1.136
